<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { t } from '../i18n'
const values=ref<Array<number|null>>([null,null,null]),copied=ref<'average'|'sum'|null>(null),listEl=ref<HTMLElement|null>(null),activeIndex=ref(0)
const valid=computed(()=>values.value.filter((v):v is number=>v!==null&&Number.isFinite(v))),sum=computed(()=>valid.value.reduce((a,b)=>a+b,0)),average=computed(()=>valid.value.length?sum.value/valid.value.length:null)
function sanitize(raw:string){const normalized=raw.replace(/[^0-9.\-]/g,'').replace(/(?!^)-/g,'');const dot=normalized.indexOf('.');return dot<0?normalized:normalized.slice(0,dot+1)+normalized.slice(dot+1).replace(/\./g,'')}
function scrollTo(index:number,focus=false){nextTick(()=>requestAnimationFrame(()=>{const list=listEl.value,input=list?.querySelector<HTMLInputElement>(`input[data-index="${index}"]`),row=input?.closest<HTMLElement>('.value-row');if(list&&row)list.scrollTo({top:Math.max(0,row.offsetTop-list.clientHeight+row.clientHeight+8),behavior:'smooth'});if(focus)setTimeout(()=>input?.focus(),120)}))}
function ensureNext(index:number){if(index===values.value.length-1){values.value.push(null);scrollTo(index)}}
function update(index:number,event:Event){activeIndex.value=index;const input=event.target as HTMLInputElement,clean=sanitize(input.value);if(clean!==input.value)input.value=clean;values.value[index]=clean===''||clean==='-'||clean==='.'?null:Number(clean);ensureNext(index)}
function focusRow(index:number,event:FocusEvent){activeIndex.value=index;ensureNext(index);const input=event.target as HTMLInputElement;if(input.dataset.justFocused!=='1'){input.dataset.justFocused='1';nextTick(()=>input.select())}}
function clickRow(event:MouseEvent){const input=event.currentTarget as HTMLInputElement;if(input.dataset.justFocused==='1'){event.preventDefault();input.select();input.dataset.justFocused='0'}}
function cleanup(){setTimeout(()=>{if(listEl.value?.contains(document.activeElement))return;while(values.value.length>3&&values.value.at(-1)===null&&values.value.at(-2)===null)values.value.pop()},0)}
function moveRow(index:number,event:KeyboardEvent){const down=event.key==='ArrowDown'||event.key==='Enter'||(event.key==='Tab'&&!event.shiftKey),up=event.key==='ArrowUp'||(event.key==='Tab'&&event.shiftKey);if(!down&&!up)return;event.preventDefault();let next=Math.max(0,index+(down?1:-1));if(next>=values.value.length)values.value.push(null);activeIndex.value=next;scrollTo(next,true)}
function wheelInput(event:WheelEvent){event.preventDefault();if(listEl.value)listEl.value.scrollTop+=event.deltaY}
function remove(index:number){values.value.splice(index,1);while(values.value.length<3)values.value.push(null);if(values.value.at(-1)!==null)values.value.push(null)}
function reset(){values.value=[null,null,null];activeIndex.value=0;copied.value=null}
async function copy(kind:'average'|'sum'){const value=kind==='average'?average.value:sum.value;if(kind==='average'&&value===null)return;try{await navigator.clipboard.writeText(format(value??0));copied.value=kind;setTimeout(()=>copied.value=null,1500)}catch{}}
function format(value:number){return Number(value.toPrecision(12)).toString()}
function trackFocus(event:FocusEvent){const element=event.target as HTMLElement;if(element.matches('.values-list input[data-index]'))activeIndex.value=Number(element.dataset.index)}
onMounted(()=>document.addEventListener('focusin',trackFocus));onBeforeUnmount(()=>document.removeEventListener('focusin',trackFocus))
</script>
<template><div class="page average-page"><div class="average-layout"><section class="average-panel values-panel"><div class="average-head"><h1>{{t('average.input')}}</h1><button @click="reset">{{t('average.reset')}}</button></div><div ref="listEl" class="values-list" @focusout="cleanup"><label v-for="(value,index) in values" :key="index" class="value-row"><span>{{index+1}}</span><input type="text" inputmode="decimal" :enterkeyhint="index===values.length-1?'done':'next'" :data-index="index" :placeholder="t('average.placeholder')" :value="value??''" @input="update(index,$event)" @focus="focusRow(index,$event)" @click="clickRow" @wheel="wheelInput" @keydown="moveRow(index,$event)"><button v-if="values.length>3||value!==null" :aria-label="t('average.remove')" @click.prevent="remove(index)">×</button></label></div></section><section class="average-panel average-result"><div class="average-result-head">{{t('average.result')}}</div><div v-if="average!==null" class="average-main"><small>{{t('average.average')}}</small><strong>{{format(average)}}</strong><button class="copy-single" @click="copy('average')">{{copied==='average'?t('average.copied'):t('average.copyAverage')}}</button></div><p v-else class="average-empty">{{t('average.empty')}}</p><div class="average-secondary"><span><small>{{t('average.sum')}}</small><b>{{format(sum)}}</b><button class="copy-single" :disabled="average===null" @click="copy('sum')">{{copied==='sum'?t('average.copied'):t('average.copySum')}}</button></span><span><small>{{t('average.count')}}</small><b>{{valid.length}}</b></span></div></section></div></div></template>
