<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { t } from '../i18n'
import NumberInput from '../components/NumberInput.vue'
import { calculateEfficiency } from '../logic/efficiency'
const form=reactive({output:null as number|null,sam:null as number|null,workers:null as number|null,hours:null as number|null,target:null as number|null})
const formulaOpen=ref(true),terminologyOpen=ref(false),result=computed(()=>calculateEfficiency(form)),touched=computed(()=>Object.values(form).some(v=>v!==null)),hasTarget=computed(()=>form.target!==null&&form.target>0)
const statusText=computed(()=>t.value(`efficiency.${result.value.status==='none'?'noTarget':result.value.status}`))
const format=(n:number|null,suffix='')=>n===null?'—':`${n.toFixed(1)}${suffix}`
function reset(){Object.assign(form,{output:null,sam:null,workers:null,hours:null,target:null})}
</script>
<template><div class="page efficiency-page"><header class="page-intro"><span class="eyebrow">{{t('efficiency.kicker')}}</span><h1>{{t('efficiency.title')}}</h1><p>{{t('efficiency.intro')}}</p></header><div class="calculator-layout"><section class="panel input-panel"><h2><span>01</span>{{t('efficiency.input')}}</h2><div class="fields-grid"><NumberInput v-model="form.output" :label="t('efficiency.output')" :hint="t('efficiency.outputHint')" :unit="t('efficiency.units.pcs')"/><NumberInput v-model="form.sam" :label="t('efficiency.sam')" :hint="t('efficiency.samHint')" :unit="t('efficiency.units.min')"/><NumberInput v-model="form.workers" :label="t('efficiency.workers')" :hint="t('efficiency.workersHint')" :unit="t('efficiency.units.people')"/><NumberInput v-model="form.hours" :label="t('efficiency.hours')" :hint="t('efficiency.hoursHint')" :unit="t('efficiency.units.hour')"/><NumberInput v-model="form.target" class="full-field" :label="t('efficiency.target')" :hint="t('efficiency.targetHint')" :unit="t('efficiency.units.percent')" :optional="t('efficiency.optional')"/></div></section><section class="panel result-panel" :class="result.status"><div class="result-top"><h2><span>02</span>{{t('efficiency.result')}}</h2><span v-if="result.valid" class="live-badge"><i></i>{{t('efficiency.live')}}</span></div><div class="primary-result"><small>{{t('efficiency.mainResult')}}</small><strong>{{result.valid?format(result.efficiency,'%'):'—'}}</strong><p v-if="!result.valid">{{touched?t('efficiency.invalid'):t('efficiency.readyHint')}}</p></div><div v-if="result.valid&&hasTarget" class="result-metrics"><div><small>{{t('efficiency.target')}}</small><b>{{format(form.target,'%')}}</b></div><div><small>{{t('efficiency.difference')}}</small><b>{{format(result.difference)}} {{t('efficiency.points')}}</b></div><div><small>{{t('efficiency.achievement')}}</small><b>{{format(result.achievement,'%')}}</b></div><div><small>{{t('efficiency.status')}}</small><b class="status-label">{{statusText}}</b></div></div><button class="reset-button" @click="reset"><span>↻</span>{{t('efficiency.reset')}}</button></section></div><section class="support-grid"><div class="support-card"><button class="support-toggle" :aria-expanded="formulaOpen" @click="formulaOpen=!formulaOpen"><span><i>ƒx</i>{{t('efficiency.formulaTitle')}}</span><b>{{formulaOpen?'−':'+'}}</b></button><div v-if="formulaOpen" class="support-content"><code>{{t('efficiency.formula')}}</code><p>{{t('efficiency.formulaNote')}}</p></div></div><div class="support-card"><button class="support-toggle" :aria-expanded="terminologyOpen" @click="terminologyOpen=!terminologyOpen"><span><i>SAM</i>{{t('efficiency.terminology')}}</span><b>{{terminologyOpen?'−':'+'}}</b></button><div v-if="terminologyOpen" class="support-content terminology"><strong>{{t('efficiency.samName')}}</strong><p>{{t('efficiency.samDefinition')}}</p><small>{{t('efficiency.samExample')}}</small></div></div></section></div></template>
