<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { t } from '../i18n'
type Entry={expression:string;value:number}
type CalcState={expression:string;solvedExpression:string;rawResult:number|null;history:Entry[];justSolved:boolean}
const expression=ref(''),solvedExpression=ref(''),rawResult=ref<number|null>(null),history=ref<Entry[]>([]),justSolved=ref(false),percentView=ref(false)
const expressionEl=ref<HTMLElement|null>(null),historyEl=ref<HTMLElement|null>(null),showAllHistory=ref(false),selectedHistory=ref<number|null>(null),fullscreenSupported=ref(true),isFullscreen=ref(false)
const cloneState=():CalcState=>({expression:expression.value,solvedExpression:solvedExpression.value,rawResult:rawResult.value,history:history.value.map(e=>({...e})),justSolved:justSolved.value})
const snapshots=ref<CalcState[]>([cloneState()]),cursor=ref(0),keys=['C','(',')','⌫','7','8','9','÷','4','5','6','×','1','2','3','−','%','0','.','+'],operators=['+','−','×','÷']
const canUndo=computed(()=>cursor.value>0),canRedo=computed(()=>cursor.value<snapshots.value.length-1),formattedResult=computed(()=>{if(rawResult.value===null)return'0';const value=percentView.value?rawResult.value*100:rawResult.value;return`${Number(value.toPrecision(12))}${percentView.value?'%':''}`}),expressionSize=computed(()=>expression.value.length>28?'small':expression.value.length>18?'medium':'large')
function applyState(state:CalcState){expression.value=state.expression;solvedExpression.value=state.solvedExpression;rawResult.value=state.rawResult;history.value=state.history.map(e=>({...e}));justSolved.value=state.justSolved;selectedHistory.value=null}
function commit(change:()=>void){change();snapshots.value=snapshots.value.slice(0,cursor.value+1);snapshots.value.push(cloneState());if(snapshots.value.length>101)snapshots.value.shift();cursor.value=snapshots.value.length-1}
function normalized(value:string){return value.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/%/g,'/100')}
function evaluate(){if(!expression.value)return;commit(()=>{try{const clean=normalized(expression.value);if(!/^[\d+\-*/().\s]+$/.test(clean))throw 0;const value=Function(`"use strict";return (${clean})`)();if(typeof value!=='number'||!Number.isFinite(value))throw 0;rawResult.value=value;solvedExpression.value=expression.value;history.value.push({expression:expression.value,value});if(history.value.length>100)history.value.shift();justSolved.value=true}catch{solvedExpression.value=expression.value;rawResult.value=null;justSolved.value=false}})}
function press(key:string){if(key==='='){evaluate();return}if(key==='C'){commit(()=>{expression.value='';solvedExpression.value='';rawResult.value=null;justSolved.value=false});return}if(key==='⌫'){if(expression.value)commit(()=>{expression.value=expression.value.slice(0,-1);justSolved.value=false});return}let current=expression.value,last=current.slice(-1);if(justSolved.value){if(/[0-9.(]/.test(key))current='';else if(rawResult.value!==null)current=String(rawResult.value)}last=current.slice(-1);if(operators.includes(key)){if(!current||last==='('){if(key!=='−')return}else if(operators.includes(last)||last==='.')return}if(key==='%'){if(!/[0-9)]/.test(last)||last==='%')return}if(key==='('&&current&&/[0-9)%]/.test(last))return;if(key===')'){const opens=(current.match(/\(/g)||[]).length,closes=(current.match(/\)/g)||[]).length;if(opens<=closes||!/[0-9)%]/.test(last))return}if(key==='.'){const part=current.split(/[+−×÷()%]/).pop()||'';if(part.includes('.'))return;if(!part)key='0.'}commit(()=>{expression.value=current+key;justSolved.value=false})}
function undo(){if(!canUndo.value)return;cursor.value--;applyState(snapshots.value[cursor.value])}
function redo(){if(!canRedo.value)return;cursor.value++;applyState(snapshots.value[cursor.value])}
function chooseHistory(index:number){selectedHistory.value=selectedHistory.value===index?null:index}
function restoreHistory(){const index=selectedHistory.value;if(index===null)return;const entry=history.value[index];commit(()=>{history.value=history.value.slice(0,index+1);expression.value=String(entry.value);rawResult.value=entry.value;solvedExpression.value=entry.expression;justSolved.value=true});selectedHistory.value=null;showAllHistory.value=false}
function deleteHistory(){const index=selectedHistory.value;if(index===null)return;commit(()=>{history.value=history.value.slice(0,index);const last=history.value.at(-1);if(last){solvedExpression.value=last.expression;rawResult.value=last.value;expression.value=String(Number(last.value.toPrecision(12)));justSolved.value=true}else{solvedExpression.value='';rawResult.value=null;expression.value='';justSolved.value=false}});selectedHistory.value=null}
function clearAll(){commit(()=>{expression.value='';solvedExpression.value='';rawResult.value=null;history.value=[];justSolved.value=false})}
function keydown(e:KeyboardEvent){if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}const map:Record<string,string>={'*':'×','/':'÷','-':'−','Enter':'=','Backspace':'⌫','Escape':'C'},key=map[e.key]??e.key;if(/^[0-9+().%]$/.test(key)||['×','÷','−','=','⌫','C'].includes(key)){e.preventDefault();press(key)}}
async function toggleFullscreen(){const doc=document as Document&{webkitFullscreenElement?:Element;webkitExitFullscreen?:()=>Promise<void>},root=document.documentElement as HTMLElement&{webkitRequestFullscreen?:()=>Promise<void>};try{if(document.fullscreenElement||doc.webkitFullscreenElement){if(document.exitFullscreen)await document.exitFullscreen();else await doc.webkitExitFullscreen?.()}else if(root.requestFullscreen)await root.requestFullscreen();else if(root.webkitRequestFullscreen)await root.webkitRequestFullscreen();else fullscreenSupported.value=false}catch{fullscreenSupported.value=false}}
function syncFullscreen(){const doc=document as Document&{webkitFullscreenElement?:Element};isFullscreen.value=Boolean(document.fullscreenElement||doc.webkitFullscreenElement)}
watch(expression,async()=>{await nextTick();requestAnimationFrame(()=>{if(expressionEl.value)expressionEl.value.scrollLeft=expressionEl.value.scrollWidth-expressionEl.value.clientWidth})});watch(()=>history.value.length,async()=>{await nextTick();requestAnimationFrame(()=>{if(historyEl.value)historyEl.value.scrollTop=historyEl.value.scrollHeight})})
onMounted(()=>{document.body.classList.add('calculator-open');fullscreenSupported.value=Boolean(document.documentElement.requestFullscreen||(document.documentElement as any).webkitRequestFullscreen);window.addEventListener('keydown',keydown);document.addEventListener('fullscreenchange',syncFullscreen);document.addEventListener('webkitfullscreenchange',syncFullscreen)});onBeforeUnmount(()=>{document.body.classList.remove('calculator-open');window.removeEventListener('keydown',keydown);document.removeEventListener('fullscreenchange',syncFullscreen);document.removeEventListener('webkitfullscreenchange',syncFullscreen)})
</script>
<template><div class="page enhanced-page"><section class="calc-upper"><aside class="calc-control-rail"><button @click="showAllHistory=true;selectedHistory=null">{{t('calculator.moreHistory')}}</button><button :disabled="rawResult===null" @click="percentView=!percentView">{{percentView?t('calculator.showDecimal'):t('calculator.showPercent')}}</button><button v-if="fullscreenSupported" @click="toggleFullscreen">{{isFullscreen?t('calculator.exitFullscreen'):t('calculator.fullscreen')}}</button><button class="clear-all" @click="clearAll">{{t('calculator.clearAll')}}</button></aside><div class="calc-content-area"><div ref="historyEl" class="calc-history"><p v-if="!history.length">{{t('calculator.noHistory')}}</p><button v-for="(entry,index) in history" :key="index" :class="{selected:selectedHistory===index}" @click="chooseHistory(index)"><span>{{entry.expression}}</span><b>= {{Number(entry.value.toPrecision(12))}}</b></button></div><div v-if="selectedHistory!==null" class="history-actions"><button @click="restoreHistory">{{t('calculator.restoreHere')}}</button><button class="delete" @click="deleteHistory">{{t('calculator.deleteFromHere')}}</button></div><div class="fixed-result"><div class="solved-line">{{solvedExpression}}</div><div ref="expressionEl" class="active-line" :class="expressionSize">{{justSolved?formattedResult:(expression||'0')}}</div></div></div></section><section class="keypad" @dblclick.prevent><button v-for="key in keys" :key="key" :class="{operator:operators.includes(key)||['%','(',')'].includes(key),utility:['C','⌫'].includes(key)}" @click="press(key)">{{key}}</button><button class="history-key" :disabled="!canUndo" @click="undo">↶ {{t('calculator.undo')}}</button><button class="history-key" :disabled="!canRedo" @click="redo">↷ {{t('calculator.redo')}}</button><button class="equals" @click="press('=')">=</button></section><div v-if="showAllHistory" class="history-modal"><div class="history-modal-head"><button class="history-back" :aria-label="t('app.back')" @click="showAllHistory=false;selectedHistory=null">←</button><h2>{{t('calculator.allHistory')}}</h2></div><div class="history-modal-list"><p v-if="!history.length">{{t('calculator.noHistory')}}</p><button v-for="(entry,index) in history" :key="index" :class="{selected:selectedHistory===index}" @click="chooseHistory(index)"><span>{{entry.expression}}</span><b>= {{Number(entry.value.toPrecision(12))}}</b></button><div v-if="selectedHistory!==null" class="history-actions modal-actions"><button @click="restoreHistory">{{t('calculator.restoreHere')}}</button><button class="delete" @click="deleteHistory">{{t('calculator.deleteFromHere')}}</button></div></div></div></div></template>
